{% set name = "triad" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6de9cb3ebd95335f650428fed46d090733b21045a7b3f2eaf8b8645d9f4b123

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - six
    - ciso8601
    - pyarrow
    - fs

test:
  imports:
    - triad
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/fugue-project/triad
  license: Apache-2.0
  license_file: LICENSE
  summary: A collection of python utility functions for Fugue projects
  doc_url: https://triad.readthedocs.org
  dev_url: https://github.com/fugue-project/triad

extra:
  recipe-maintainers:
    - kvnkho
    - goodwanghan
    - rdmolony
