{% set name = "triad" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fugue-project/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: e2e64a5b75d6b65acad4d1eb1ed4877619ae0e724d31c1992c7d145052d4cb07

build:
  number: 0
  # pyarrow is not supported on s390x, hence skipping this arch.
  skip: true  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - pandas >=1.3.5
    - six
    - pyarrow >=6.0.1
    - fsspec >=2022.5.0
    - fs
    # imported in triad/utils/pyarrow.py
    - packaging

test:
  source_files:
    - tests
  imports:
    - triad
  requires:
    - cloudpickle
    - pip
    - pytest
    - pytest-mock
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests

about:
  home: https://github.com/fugue-project/triad
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A collection of python utility functions for Fugue projects
  description: A collection of python utility functions for Fugue projects
  doc_url: https://triad.readthedocs.io
  dev_url: https://github.com/fugue-project/triad

extra:
  recipe-maintainers:
    - charlesbluca
    - thewchan
    - kvnkho
    - goodwanghan
    - rdmolony
