{% set name = "triad" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4dff41ffbb98bad4d9741c9dd632890cdfe0b873f23d76d2b5f9ca41d4440a7

build:
  number: 0
  # pyarrow is not supported on s390x, hence skipping this arch.
  skip: true  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python 
    - ciso8601
    - fs
    - importlib_metadata  # [py<38]
    - numpy
    - pandas >=1.2.0
    - pyarrow
    - six

test:
  source_files:
    - tests
  imports:
    - triad
  requires:
    - cloudpickle
    - pip
    - pytest
    - pytest-mock
  commands:
    - pip check
    # Two tests fail for python 3.11 when a function from cloudpickle package is used, required for running tests. 
    # It is possible that we need to update cloudpickle to the latest version. Switching off these tests for now. 
    - pytest -vvv --capture=tee-sys tests -k "not (test_conditional_dispatcher or test_runonce)"  # [py>=311]
    - pytest -vvv --capture=tee-sys tests  # [py<311]

about:
  home: https://github.com/fugue-project/triad
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A collection of python utility functions for Fugue projects
  description: A collection of python utility functions for Fugue projects
  doc_url: https://triad.readthedocs.io
  dev_url: https://github.com/fugue-project/triad

extra:
  recipe-maintainers:
    - charlesbluca
    - thewchan
    - kvnkho
    - goodwanghan
    - rdmolony
