{% set name = "triad" %}
{% set version = "1.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fugue-project/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 27c07b5b76e9562a0a0d7e6b1c87eb18573306be281a8002337675e3fba80ecc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0,<81
    - wheel
  run:
    - python
    - numpy
    - pandas >=2
    - six
    - pyarrow >=6.0.1
    - fsspec >=2022.5.0
    # imported in triad/utils/pyarrow.py
    # https://github.com/fugue-project/triad/blob/v1.0.2/triad/utils/pyarrow.py#L10
    - packaging

test:
  # downstreams:
  #   - adagio
  #   - fugue
  #   - qpd
  #   - fugue-sql-antlr
  source_files:
    - tests
  imports:
    - triad
  requires:
    - cloudpickle
    - pip
    - pytest
    - pytest-mock
    # Setuptools is required for the tests to run.
    # E   ModuleNotFoundError: No module named 'pkg_resources'
    - setuptools <81
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests

about:
  home: https://github.com/fugue-project/triad
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A collection of python utility functions for Fugue projects
  description: A collection of python utility functions for Fugue projects
  doc_url: https://triad.readthedocs.io
  dev_url: https://github.com/fugue-project/triad

extra:
  recipe-maintainers:
    - charlesbluca
    - thewchan
    - kvnkho
    - goodwanghan
    - rdmolony
