{% set name = "triad" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fugue-project/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0c6dc83e9fa432125bae317fa075b366548916e4231b2d5ee3f0a798c7eda16e

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - pandas >=1.3.5
    - six
    - pyarrow >=6.0.1
    - fsspec >=2022.5.0
    # imported in triad/utils/pyarrow.py
    - packaging

test:
  source_files:
    - tests
  imports:
    - triad
  requires:
    - cloudpickle
    - pip
    - pytest
    - pytest-mock
    # Setuptools is required for the tests to run.
    # E   ModuleNotFoundError: No module named 'pkg_resources'
    - setuptools
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests

about:
  home: https://github.com/fugue-project/triad
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A collection of python utility functions for Fugue projects
  description: A collection of python utility functions for Fugue projects
  doc_url: https://triad.readthedocs.io
  dev_url: https://github.com/fugue-project/triad

extra:
  recipe-maintainers:
    - charlesbluca
    - thewchan
    - kvnkho
    - goodwanghan
    - rdmolony
